name: windows-ni CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-ni

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync --group hardw --frozen

      - name: Tests
        run: uv run pytest --run-ni --no-cov
