[Working_mode]
Work_around-the-clock = false

[Work_schedule]
start = 8:00 # Just typical value (to specify actual value)!!!
stop = 20:00 # Just typical value (to specify actual value)!!!

[Data_transferring_time]
start = 23:00 # Just possible value


; Here could be placed additional settings