collector_config:
  port: 8000
devices:
  - class_path: toy_device.ToyAcousticDevice
    init_args:
      config:
        device_id: "toy_acoustic_device"
        sample_rate: 44100
        duration: 1