api_port: 8113
s3_sync_service:
  class_path: S3SyncServiceBase
  init_args:
    config:
      data_root: data
      upload_every_n_files: 60
      upload_every_seconds: 600
      delete_after_upload: false
    client:
      class_path: base.s3_client.YandexS3Client
      init_args:
        config:
          region: ru-central1
          bucket: test-monitoring
          prefix: obto3
          # access_key: ${YANDEX_S3_ACCESS_KEY}
          # secret_key: ${YANDEX_S3_SECRET_KEY}
